# Generated by Django 5.0 on 2024-01-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='name',
            field=models.CharField(default='hostel fee', max_length=10),
            preserve_default=False,
        ),
    ]
