# Generated by Django 5.0 on 2023-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeat',
            name='parent_number',
            field=models.CharField(max_length=11),
        ),
    ]
