# Generated by Django 5.0 on 2024-01-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_alter_exeat_parent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostel.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostel.faculty'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostel.gender'),
        ),
    ]
