# Generated by Django 5.0 on 2024-01-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_amount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='name',
        ),
        migrations.AlterField(
            model_name='amount',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
