# Generated by Django 5.0 on 2023-12-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_remove_exeat_is_approved_exeat_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], max_length=4)),
                ('bunk', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Hostel.bunk')),
            ],
            options={
                'unique_together': {('bunk', 'position')},
            },
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
