# Generated by Django 5.0 on 2023-12-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0007_bedspace_delete_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
    ]
