# Generated by Django 5.0 on 2023-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0008_remove_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedspace',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
