# Generated by Django 5.0 on 2023-12-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0009_bedspace_is_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostel.bunk'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostel.bedspace'),
        ),
    ]
