# Generated by Django 5.0 on 2023-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0010_customuser_bunk_customuser_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel_name',
            field=models.CharField(default='male new hostel', max_length=100),
        ),
    ]
