# Generated by Django 5.0 on 2023-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0011_complaint_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeat',
            name='parent_number',
            field=models.CharField(max_length=100),
        ),
    ]
