# Generated by Django 5.0 on 2023-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0012_alter_exeat_parent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeat',
            name='parent_number',
            field=models.FloatField(),
        ),
    ]
